<a href="https://colab.research.google.com/github/MDRafiqul-Islam/Large-Scale-Data-Management/blob/main/SVD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import math
import numpy as np

In [ ]:
def eye(n):
  lst = [[] for _ in range(n)]
  # Filling the main diagonal with ones and the rest with zeros
  for i in range(n):
    for j in range(n):
      if i == j:
        lst[i].append(1)
      else:
        lst[i].append(0)
  #Converting the list to a NumPy array
  return np.array(lst)

https://dspace.mit.edu/bitstream/handle/1721.1/75282/18-335j-fall-2006/contents/lecture-notes/lec16.pdf

https://www.youtube.com/watch?v=d32WV1rKoVk&ab_channel=MITOpenCourseWare

https://cse.buffalo.edu/faculty/miller/Courses/CSE633/Eric-Mikida-Fall-2011.pdf

In [ ]:
def qr_algorithm(A):
  n = A.shape[0]
  Q = eye(n)

  for i in range(n - 1):
    # Computing the QR decomposition of the matrix A
    R = np.zeros((n, n))
    Q_i = np.zeros((n, n))

    for j in range(n):
      R[j, j] = np.sqrt(np.sum(A[:, j] ** 2))
      Q_i[:, j] = A[:, j] / R[j, j]
      R[j, i] = np.sum(Q_i[:, j] * A[:, i])
      A[:, i] = A[:, i] - R[j, i] * Q_i[:, j]
    
    A = R @ Q_i
    Q = Q @ Q_i
  
  # The eigenvalues of A are the diagonal elements of A
  eigenvalues = np.diagonal(A)
  
  # The eigenvectors are the columns of Q
  eigenvectors = Q
  
  return eigenvalues, eigenvectors

In [ ]:
def svd(A):
    m, n = len(A), len(A[0])
    AtA = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            for k in range(m):
                AtA[i][j] += A[k][i]*A[k][j]
    eigenvalues, eigenvectors = qr_algorithm(AtA)
    singular_values = [np.sqrt(abs(eigenvalue)) for eigenvalue in eigenvalues]
    V = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            V[i][j] = eigenvectors[i][j]
    U = np.zeros((n, m))
    for i in range(n):
        for j in range(m):
            U[i][j] = A[j][i]/singular_values[i]
    return U, singular_values, V

In [ ]:
# Defining the matrix M
r = int(input("Enter the number of rows: "))
c = int(input("Enter the number of columns: "))
if r != c:
  raise ValueError('If the matrix M is not square, then it cannot be factorized using traditional matrix factorization techniques such as SVD or QR decomposition.')
A = [[int(input('Please Input the number for position ({},{}): '.format(x, y))) for x in range(c)] for y in range(r)]
M = np.array(A).reshape(r, c)
# M = np.random.rand(12, 12)
# Calculate the SVD of M
U, S, Vt = svd(M) 
print(U)
print(S)
print(Vt)

Enter the number of rows: 3
Enter the number of columns: 3
Please Input the number for position (0,0): 1
Please Input the number for position (1,0): 2
Please Input the number for position (2,0): 3
Please Input the number for position (0,1): 4
Please Input the number for position (1,1): 5
Please Input the number for position (2,1): 6
Please Input the number for position (0,2): 7
Please Input the number for position (1,2): 8
Please Input the number for position (2,2): 9
[[ 0.0792548   0.3170192   0.5547836 ]
 [ 4.44859073 11.12147682 17.79436292]
 [ 0.26726124  0.53452248  0.80178373]]
[12.617532353748057, 0.44958057996200973, 11.224972160321823]
[[ 0.80529302 -0.20994376  0.80329344]
 [ 0.96087876 -0.24420165  0.95855184]
 [ 1.1164645  -0.27845954  1.11381023]]


In [ ]:
# Calculating M1 and M2 from the SVD
M1 = U @ S
M2 = Vt

print('M1 Value is: ',M1)
print('M2 Value is: ',M2)

M1 Value is:  [  7.36995612 260.8714658   12.6124883 ]
M2 Value is:  [[ 0.80529302 -0.20994376  0.80329344]
 [ 0.96087876 -0.24420165  0.95855184]
 [ 1.1164645  -0.27845954  1.11381023]]


**Another way using eigh function**

In [ ]:
# import numpy as np
# from scipy.linalg import eigh

# r = int(input("Enter the number of rows: "))
# c = int(input("Enter the number of columns: "))
# if r != c:
#   raise ValueError('If the matrix M is not square, then it cannot be factorized using traditional matrix factorization techniques such as SVD or QR decomposition.')
# A = [[int(input('Please Input the number for position ({},{}): '.format(x, y))) for x in range(c)] for y in range(r)]
# M = np.array(A).reshape(r, c)

# M_T = M.T

# MTM = np.dot(M_T, M)

# eigenvalues, eigenvectors = eigh(MTM)

# idx = eigenvalues.argsort()[::-1]
# eigenvalues = eigenvalues[idx]
# eigenvectors = eigenvectors[:,idx]

# M1 = eigenvectors
# M2 = np.diag(np.sqrt(eigenvalues))

# M1 = U @ S
# M2 = Vt

# print('M1 Value is: ',M1)
# print('M2 Value is: ',M2)
